# -----------------------------------------------------------------------------
# CONFIGURACIÓN DE FINANCIACIÓN MYCN18 - DESARROLLADOR ÚNICO (Luke1606)
# -----------------------------------------------------------------------------
# Esta configuración dirige todo el apoyo al desarrollador individual, Luke1606, 
# ya que las cuentas de plataformas externas (Patreon, Ko-fi) no están activas actualmente.

# Plataformas de Apoyo Esenciales (Centradas en Código)

github: [Luke1606]
# GitHub Sponsors es el canal principal para apoyar directamente al creador, Luke1606.

# Plataformas de Donación Rápida y Proyecto (Actualmente inactivas/no establecidas)

patreon: # No activo.
open_collective: # No establecido.
ko_fi: # No activo.
tidelift: # No aplicable para el alcance de este proyecto.
community_bridge: # No aplicable.
liberapay: # No activo.
issuehunt: # No aplicable.
lfx_crowdfunding: # No aplicable.
polar: # No aplicable.
buy_me_a_coffee: # No activo.

# Reconocimiento Técnico
# Esto financia automáticamente al mantenedor en función del uso.

thanks_dev: Luke1606 

# Enlaces Universales Personalizados
# Estos enlaces proporcionan a los usuarios que no están en GitHub (por ejemplo, usuarios visuales/nodos) 
# formas sencillas de donar y opciones de servicio profesional.

custom: [
  'https://paypal.me/pendiente', # Enlace de donación universal. (aun no tengo cuenta)
  'https://Luke1606.dev/mycn18-consulting' # Enlace directo para consultoría profesional u horas de soporte.
]
# -----------------------------------------------------------------------------
