# -----------------------------------------------------------------------------
# CONFIGURACIÓN DE FINANCIACIÓN MYCN18 - DESARROLLADOR ÚNICO (Luke1606)
# -----------------------------------------------------------------------------
# Esta configuración dirige todo el apoyo al desarrollador individual, Luke1606, 
# ya que las cuentas de plataformas externas (Patreon, Ko-fi) no están activas actualmente.

# Plataformas de Apoyo Esenciales (Centradas en Código)

github: [Luke1606]
# GitHub Sponsors es el canal principal para apoyar directamente al creador, Luke1606.

# Plataformas de Donación Rápida y Proyecto (Actualmente inactivas/no establecidas)

# Reconocimiento Técnico
# Esto financia automáticamente al mantenedor en función del uso.

# Enlaces Universales Personalizados
# Estos enlaces proporcionan a los usuarios que no están en GitHub (por ejemplo, usuarios visuales/nodos) 
# formas sencillas de donar y opciones de servicio profesional.

custom: [
  'https://paypal.me/pendiente', # Enlace de donación universal. (aun no tengo cuenta)
  'https://Luke1606.dev/mycn18-consulting' # Enlace directo para consultoría profesional u horas de soporte.
]
# -----------------------------------------------------------------------------
