# -----------------------------------------------------------------------------
# CONFIGURACIÓN DE FINANCIACIÓN MYCN18 - DESARROLLADOR ÚNICO (Luke1606)
# -----------------------------------------------------------------------------
# Esta configuración dirige todo el apoyo al desarrollador individual, Luke1606.

# Plataformas de Apoyo Esenciales (Centradas en Código)

github: [Luke1606]
# GitHub Sponsors es el canal principal para apoyar directamente al creador.

# Plataformas de Proyecto y Donación (Activas)

open_collective: MyCn18
thanks_dev: u/gh/luke1606 

# Enlaces Universales Personalizados
# Estos enlaces proporcionan a los usuarios que no están en GitHub formas sencillas de donar
# y opciones de servicio profesional.

custom: [
  'https://paypal.me/paypalantonioernestoalmaguerzayas@gmail.com',
  'https://Luke1606.dev/mycn18-consulting' # Enlace directo para consultoría profesional u horas de soporte.
]
# -----------------------------------------------------------------------------